### ISSUE TITLE
Resetting usb hub

### ISSUE THREAD

**Issue by sskorol** [isonic1/appium-mobile-grid#2]
Hi @isonic1,

In your Selenium Camp 16 talk you've mentioned issues with loosing connectivity with real devices connected to usb hub. I've faced with the same problem. Only cable unplugging / plugging helps. As a solution you were resetting the hub programmatically before each test somehow. Could you please share the code to perform this operation?

Thanks,
Sergey

**Comment by isonic1** [comment]
Hi @sskorol 
I actually bought a programmable power strip to power cycle the USB hubs prior to each test run. This would then reset the stale ADB connections. Basically, it's just a curl POST to the powerstrip to tell it to turn on or off. I hope this helps!

http://energenie.com/item.aspx?id=7557

**Comment by sskorol** [comment]
@isonic1 thanks, will check it :)
